# сделал Дамир Мухаметзянов

RES = WIDTH, HEIGHT = 1250, 850
RES_MENU = (800, 600)
TILE = 50
FPS = 60
COLS, ROWS = WIDTH // TILE, HEIGHT // TILE
GRAVITY = 1
CORDS = [(WIDTH // 2, HEIGHT // 2), (WIDTH // 3, HEIGHT // 3), (WIDTH // 3 * 2, HEIGHT // 3)]
NAME_DB = 'SQL/labirint_db.db'
LOG = 'log'
MAPS = 'maps'
ACCOUNTS = 'accounts'
ID = 'id'
ACCOUNT = 'account'
PLAYER_X = 'player_x'
PLAYER_Y = 'player_y'
ENEMY_X = 'enemy_x'
ENEMY_Y = 'enemy_y'
MAP = 'map'
LOGIN = 'login'
PASSWORD = 'password'
FONT_RES = 130
GOLD = (255, 204, 0)
RED_COLOR = (255, 0, 0)
ONE_OF_THREE = 3
OME_OF_FOUR = 4
ONE_ITERATION = 1
ONE_COORD = 1
ZERO = 0
ONE = 1
SPAWN_PLAYER = (1, 1)
SPAWN_ENEMY = (23, 1)
MOVE_LEFT = -1, 0
MOVE_RIGHT = 1, 0
MOVE_UP = 0, -1
MOVE_DOWN = 0, 1
BIG_ITERATION = 100
SMALL_ITERATION = 25
NUM_FIRE_FACE = 2
